# Generated by Django 3.0.5 on 2020-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('sobre', models.TextField(blank=True, verbose_name='Descricao reduzida')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Data de Inicio')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Inserir Imagem')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
