# Generated by Django 3.0.5 on 2020-04-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Cursos',
        ),
    ]
