# Generated by Django 3.0.5 on 2020-05-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anunciocurso',
            table='comentarios_curso',
        ),
    ]
