# Generated by Django 3.0.5 on 2020-05-19 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20200511_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('numero', models.PositiveIntegerField(blank=True, verbose_name='Numero da aula')),
                ('data_disponibilizacao', models.DateField(blank=True, null=True, verbose_name='Data disponibilização')),
                ('data_licao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licoes', to='cursos.Curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-data_inscricao'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterField(
            model_name='anunciocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_anuncios', to='cursos.Curso', verbose_name='Curso'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('midia', models.TextField(blank=True, verbose_name='Midia')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='material/licao', verbose_name='Arquivo')),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='cursos.Licao', verbose_name='Licao')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
    ]
