# Generated by Django 3.0.5 on 2020-05-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20200519_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licao',
            name='numero',
            field=models.IntegerField(blank=True, default=0, verbose_name='Numero da aula'),
        ),
    ]
