# Generated by Django 3.0.5 on 2020-04-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20200414_0306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
    ]
