# Generated by Django 3.0.5 on 2020-04-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20200416_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
