# Generated by Django 3.0.5 on 2020-04-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_auto_20200425_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='sobre',
            field=models.TextField(blank=True, verbose_name='Descricao reduzida'),
        ),
    ]
